#ifndef LOGCATEGORIES_H
#define LOGCATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(viscaLog)
Q_DECLARE_LOGGING_CATEGORY(gsLog)
Q_DECLARE_LOGGING_CATEGORY(uiLog)

#endif // GLOGCATEGORIES_H
