#ifndef LOGCATEGORIES_H
#define LOGCATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(viscaWarning);
Q_DECLARE_LOGGING_CATEGORY(viscaInfo);
Q_DECLARE_LOGGING_CATEGORY(gstreamerWarning);
Q_DECLARE_LOGGING_CATEGORY(gstreamerInfo);

#endif // GLOGCATEGORIES_H
